# Generated by Django 4.2.4 on 2025-01-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=8)),
                ('inn', models.CharField(blank=True, max_length=9, null=True)),
                ('pnfl', models.CharField(blank=True, max_length=14, null=True)),
                ('json_data', models.JSONField(blank=True, default=dict, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
